language: php

matrix:
  include:
    - php: 7.2
      env: LARAVEL=55
    - php: 7.2
      env: LARAVEL=56
    - php: 7.2
      env: LARAVEL=57
    - php: 7.2
      env: LARAVEL=58
    - php: 7.3
      env: LARAVEL=55
    - php: 7.3
      env: LARAVEL=56
    - php: 7.3
      env: LARAVEL=57
    - php: 7.3
      env: LARAVEL=58

before_script:
  - composer install

script:
  # Packages: Laravel 5.5.x
  - if [ "$LARAVEL" = "55" ] ; then composer require "phpunit/phpunit:6.*" --no-update ; fi
  - if [ "$LARAVEL" = "55" ] ; then composer require "laravel/framework:5.5.*" --no-update ; fi
  - if [ "$LARAVEL" = "55" ] ; then composer require "orchestra/database:3.5.*" --no-update ; fi
  - if [ "$LARAVEL" = "55" ] ; then composer require "orchestra/testbench:3.5.*" --no-update ; fi
  # Packages: Laravel 5.6.x
  - if [ "$LARAVEL" = "56" ] ; then composer require "phpunit/phpunit:7.*" --no-update ; fi
  - if [ "$LARAVEL" = "56" ] ; then composer require "laravel/framework:5.6.*" --no-update ; fi
  - if [ "$LARAVEL" = "56" ] ; then composer require "orchestra/database:3.6.*" --no-update ; fi
  - if [ "$LARAVEL" = "56" ] ; then composer require "orchestra/testbench:3.6.*" --no-update ; fi
  # Packages: Laravel 5.7.x
  - if [ "$LARAVEL" = "57" ] ; then composer require "phpunit/phpunit:7.*" --no-update ; fi
  - if [ "$LARAVEL" = "57" ] ; then composer require "laravel/framework:5.7.*" --no-update ; fi
  - if [ "$LARAVEL" = "57" ] ; then composer require "orchestra/database:3.7.*" --no-update ; fi
  - if [ "$LARAVEL" = "57" ] ; then composer require "orchestra/testbench:3.7.*" --no-update ; fi
  # Packages: Laravel 5.8.x
  - if [ "$LARAVEL" = "58" ] ; then composer require "phpunit/phpunit:8.*" --no-update ; fi
  - if [ "$LARAVEL" = "58" ] ; then composer require "laravel/framework:5.8.*" --no-update ; fi
  - if [ "$LARAVEL" = "58" ] ; then composer require "orchestra/database:3.8.*" --no-update ; fi
  - if [ "$LARAVEL" = "58" ] ; then composer require "orchestra/testbench:3.8.*" --no-update ; fi
  # Packages: Update
  - composer update --prefer-source --no-interaction
  # Tests: Run
  - php vendor/phpunit/phpunit/phpunit # use the phpunit specified in the composer.json so local and ci use the same version

notifications:
  email: false